// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhaNTGSXmrAE4DNJa9nmwCEaVxStW7L4',
    appId: '1:562466778827:web:cc6acd248af63b79f1f54e',
    messagingSenderId: '562466778827',
    projectId: 'movie-e6239',
    authDomain: 'movie-e6239.firebaseapp.com',
    storageBucket: 'movie-e6239.appspot.com',
    measurementId: 'G-2L2KG285RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVlMzY8hrp11vc1mVKJHaAJfr_HxWnhZk',
    appId: '1:562466778827:android:eaea001371ba91d0f1f54e',
    messagingSenderId: '562466778827',
    projectId: 'movie-e6239',
    storageBucket: 'movie-e6239.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK7kIMhnME-R5rzj_QI32sICT9OdxYAQ8',
    appId: '1:562466778827:ios:49eff118decf9ceff1f54e',
    messagingSenderId: '562466778827',
    projectId: 'movie-e6239',
    storageBucket: 'movie-e6239.appspot.com',
    iosClientId: '562466778827-1u9h7c976mlbmhrvbrfgj2tapcs1av06.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK7kIMhnME-R5rzj_QI32sICT9OdxYAQ8',
    appId: '1:562466778827:ios:49eff118decf9ceff1f54e',
    messagingSenderId: '562466778827',
    projectId: 'movie-e6239',
    storageBucket: 'movie-e6239.appspot.com',
    iosClientId: '562466778827-1u9h7c976mlbmhrvbrfgj2tapcs1av06.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieInfo',
  );
}
